{
    "Layout": "TreeLayout",
    "NodeTypes": [
            {"Id":"Person","Name":"人员", "DefaultImage":"test/images/default.png","Properties": [{"Key": "name","Name": "名称", "IsHidden": "false"},
                                                                                              {"Key": "age","Name": "年龄", "IsHidden": "true"},
                                                                                              {"Key": "position","Name": "职位", "IsHidden": "true"}]},
            {"Id":"Airplane","Name":"飞机", "DefaultImage":"test/images/Airplane.jpg","Properties": [{"Key": "no","Name": "编号", "IsHidden": "false"},
                                                                                                 {"Key": "fromCity","Name": "出发城市", "IsHidden": "true"},
                                                                                                 {"Key": "toCity","Name": "到达城市", "IsHidden": "true"}]},
            {"Id":"Hotel","Name":"酒店", "DefaultImage":"test/images/Hotel.jpg","Properties": [{"Key": "no","Name": "编号", "IsHidden": "false"},
                                                                                                 {"Key": "fromCity","Name": "所在城市", "IsHidden": "true"}]}
    ],
    "LinkTypes": [
            {"Id":"Person_Person", "Name": "人际关系","Color": "black","Thickness": "3","FromArrowType": "","ToArrowType": "Standard","Properties": [{"Key": "type","Name": "类型","IsHidden": "true"},
                                                                                                                                                         {"Key": "relation","Name": "关系","IsHidden": "false"}]},
            {"Id":"Person_Airplane", "Name": "航空旅行","Color": "blue","Thickness": "1","FromArrowType": "","ToArrowType": "OpenTriangle","Properties": [{"Key": "reason","Name": "目的","IsHidden": "true"},
                                                                                                                         {"Key": "time","Name": "时间","IsHidden": "false"}]},
            {"Id":"Person_Hotel", "Name": "住宿酒店","Color": "blue","Thickness": "1","FromArrowType": "","ToArrowType": "OpenTriangle","Properties": [{"Key": "reason","Name": "目的","IsHidden": "true"},
                                                                                                                         {"Key": "time","Name": "时间","IsHidden": "false"}]}
    ],
    "Nodes": [
            {"Id":"Person_41","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},
                                                                                                  {"Key": "age","Value": "21"},
                                                                                                  {"Key": "position","Value": "CEO"}]},
            {"Id":"Person_42","NodeTypeId": "Person","Image": "test/images/HS2.png","PropertyValues": [{"Key": "name","Value": "person 22"},
                                                                                                  {"Key": "age","Value": "22"},
                                                                                                  {"Key": "position","Value": "VP Marketing/Sales"}]},
            {"Id":"Person_43","NodeTypeId": "Person","Image": "test/images/HS3.png","PropertyValues": [{"Key": "name","Value": "person 23"},
                                                                                                  {"Key": "age","Value": "23"},
                                                                                                  {"Key": "position","Value": "VP Marketing/Sales"}]},
            {"Id":"Person_44","NodeTypeId": "Person","Image": "test/images/HS4.png","PropertyValues": [{"Key": "name","Value": "person 24"},
                                                                                                  {"Key": "age","Value": "24"},
                                                                                                  {"Key": "position","Value": "VP Marketing/Sales"}]},
            {"Id":"Person_45","NodeTypeId": "Person","Image": "test/images/HS5.png","PropertyValues": [{"Key": "name","Value": "person 22"},
                                                                                                  {"Key": "age","Value": "22"},
                                                                                                  {"Key": "position","Value": "VP Marketing/Sales"}]},
            {"Id":"Person_46","NodeTypeId": "Person","Image": "test/images/HS6.png","PropertyValues": [{"Key": "name","Value": "person 23"},
                                                                                                  {"Key": "age","Value": "23"},
                                                                                                  {"Key": "position","Value": "VP Marketing/Sales"}]},
            {"Id":"Person_47","NodeTypeId": "Person","Image": "test/images/HS7.png","PropertyValues": [{"Key": "name","Value": "person 24"},
                                                                                                  {"Key": "age","Value": "24"},
                                                                                                  {"Key": "position","Value": "VP Marketing/Sales"}]},
            {"Id":"Person_48","NodeTypeId": "Person","Image": "test/images/HS8.png","PropertyValues": [{"Key": "name","Value": "person 22"},
                                                                                                  {"Key": "age","Value": "22"},
                                                                                                  {"Key": "position","Value": "VP Marketing/Sales"}]},
            {"Id":"Person_49","NodeTypeId": "Person","Image": "test/images/HS9.png","PropertyValues": [{"Key": "name","Value": "person 23"},
                                                                                                  {"Key": "age","Value": "23"},
                                                                                                  {"Key": "position","Value": "VP Marketing/Sales"}]},
            {"Id":"Person_50","NodeTypeId": "Person","Image": "test/images/HS10.png","PropertyValues": [{"Key": "name","Value": "person 24"},
                                                                                                  {"Key": "age","Value": "24"},
                                                                                                  {"Key": "position","Value": "VP Marketing/Sales"}]}
    ],
    "Links": [
            {"Id":"Person_24_Person_41","FromId": "Person_24","ToId": "Person_41","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},
                                                                                                                             {"Key": "relation","Value": "同事"}]},
            {"Id":"Person_24_Person_42","FromId": "Person_24","ToId": "Person_42","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},
                                                                                                                             {"Key": "relation","Value": "下属"}]},
            {"Id":"Person_24_Person_43","FromId": "Person_24","ToId": "Person_43","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},
                                                                                                                             {"Key": "relation","Value": "师傅"}]},
            {"Id":"Person_24_Person_44","FromId": "Person_24","ToId": "Person_44","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},
                                                                                                                             {"Key": "relation","Value": "上司"}]},
            {"Id":"Person_24_Person_45","FromId": "Person_24","ToId": "Person_45","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},
                                                                                                                             {"Key": "relation","Value": "同事"}]},
        {"Id":"Person_24_Person_46","FromId": "Person_24","ToId": "Person_46","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},
                                                                                                                         {"Key": "relation","Value": "下属"}]},
        {"Id":"Person_24_Person_47","FromId": "Person_24","ToId": "Person_47","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},
                                                                                                                         {"Key": "relation","Value": "师傅"}]},
        {"Id":"Person_24_Person_48","FromId": "Person_24","ToId": "Person_48","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},
                                                                                                                         {"Key": "relation","Value": "上司"}]},
            {"Id":"Person_24_Person_49","FromId": "Person_24","ToId": "Person_49","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},
                                                                                                                             {"Key": "relation","Value": "同事"}]},
        {"Id":"Person_24_Person_50","FromId": "Person_24","ToId": "Person_50","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},
                                                                                                                         {"Key": "relation","Value": "下属"}]}
    ]
}
