{
    "Layout": "TreeLayout",
    "NodeTypes": [
            {"Id":"Person","Name":"人员", "DefaultImage":"test/images/default.png","Properties": [{"Key": "name","Name": "名称", "IsHidden": "false"},
                                                                                              {"Key": "age","Name": "年龄", "IsHidden": "true"},
                                                                                              {"Key": "position","Name": "职位", "IsHidden": "true"}]},
            {"Id":"Airplane","Name":"飞机", "DefaultImage":"test/images/Airplane.jpg","Properties": [{"Key": "no","Name": "编号", "IsHidden": "false"},
                                                                                                 {"Key": "fromCity","Name": "出发城市", "IsHidden": "true"},
                                                                                                 {"Key": "toCity","Name": "到达城市", "IsHidden": "true"}]},
            {"Id":"Hotel","Name":"酒店", "DefaultImage":"test/images/Hotel.jpg","Properties": [{"Key": "no","Name": "编号", "IsHidden": "false"},
                                                                                                 {"Key": "fromCity","Name": "所在城市", "IsHidden": "true"}]}
    ],
    "LinkTypes": [
            {"Id":"Person_Person", "Name": "人际关系","Color": "black","Thickness": "3","FromArrowType": "","ToArrowType": "Standard","Properties": [{"Key": "type","Name": "场合","IsHidden": "true"},
                                                                                                                                                         {"Key": "relation","Name": "关系","IsHidden": "false"}]},
            {"Id":"Person_Airplane", "Name": "航空旅行","Color": "blue","Thickness": "1","FromArrowType": "","ToArrowType": "OpenTriangle","Properties": [{"Key": "reason","Name": "目的","IsHidden": "true"},
                                                                                                                         {"Key": "time","Name": "时间","IsHidden": "false"}]},
            {"Id":"Person_Hotel", "Name": "住宿酒店","Color": "blue","Thickness": "1","FromArrowType": "","ToArrowType": "OpenTriangle","Properties": [{"Key": "reason","Name": "目的","IsHidden": "true"},
                                                                                                                         {"Key": "time","Name": "时间","IsHidden": "false"}]}
    ],
    "Nodes": [
            {"Id":"Person_1","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_2","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_3","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_4","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_5","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_6","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_7","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_8","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_9","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_10","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_11","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_12","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_13","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_14","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_15","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_16","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_17","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_18","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_19","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_20","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_21","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_22","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_23","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_24","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_25","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_26","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_27","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_28","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_29","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_30","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_31","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_32","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_33","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_34","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_35","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_36","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_37","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_38","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_39","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_40","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_41","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_42","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_43","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_44","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_45","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_46","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_47","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_48","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_49","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_50","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_51","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_52","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_53","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_54","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_55","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_56","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_57","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_58","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_59","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_60","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_61","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_62","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_63","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_64","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_65","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_66","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_67","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_68","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_69","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_70","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_71","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_72","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_73","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_74","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_75","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_76","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_77","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_78","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_79","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_80","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_81","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_82","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_83","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_84","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_85","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_86","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_87","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_88","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_89","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_90","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_91","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_92","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_93","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_94","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_95","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_96","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_97","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_98","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_99","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]},
{"Id":"Person_100","NodeTypeId": "Person","Image": "test/images/HS1.png","PropertyValues": [{"Key": "name","Value": "person 21"},{"Key": "age","Value": "21"},{"Key": "position","Value": "CEO"}]}





    ],
    "Links": [
  {"Id":"Person_1_Person_2","FromId": "Person_1","ToId": "Person_2","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_3","FromId": "Person_1","ToId": "Person_3","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_4","FromId": "Person_1","ToId": "Person_4","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_5","FromId": "Person_1","ToId": "Person_5","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_6","FromId": "Person_1","ToId": "Person_6","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_7","FromId": "Person_1","ToId": "Person_7","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_8","FromId": "Person_1","ToId": "Person_8","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_9","FromId": "Person_1","ToId": "Person_9","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_10","FromId": "Person_1","ToId": "Person_10","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_11","FromId": "Person_1","ToId": "Person_11","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_12","FromId": "Person_1","ToId": "Person_12","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_13","FromId": "Person_1","ToId": "Person_13","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_14","FromId": "Person_1","ToId": "Person_14","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_15","FromId": "Person_1","ToId": "Person_15","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_16","FromId": "Person_1","ToId": "Person_16","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_17","FromId": "Person_2","ToId": "Person_17","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_18","FromId": "Person_2","ToId": "Person_18","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_19","FromId": "Person_2","ToId": "Person_19","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_20","FromId": "Person_2","ToId": "Person_20","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_21","FromId": "Person_2","ToId": "Person_21","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_22","FromId": "Person_2","ToId": "Person_22","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_23","FromId": "Person_2","ToId": "Person_23","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_24","FromId": "Person_2","ToId": "Person_24","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_25","FromId": "Person_2","ToId": "Person_25","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_26","FromId": "Person_2","ToId": "Person_26","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_27","FromId": "Person_2","ToId": "Person_27","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_28","FromId": "Person_2","ToId": "Person_28","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_29","FromId": "Person_2","ToId": "Person_29","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_30","FromId": "Person_2","ToId": "Person_30","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_31","FromId": "Person_2","ToId": "Person_31","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_32","FromId": "Person_3","ToId": "Person_32","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_33","FromId": "Person_3","ToId": "Person_33","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_34","FromId": "Person_3","ToId": "Person_34","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_35","FromId": "Person_3","ToId": "Person_35","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_36","FromId": "Person_3","ToId": "Person_36","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_37","FromId": "Person_3","ToId": "Person_37","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_38","FromId": "Person_3","ToId": "Person_38","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_39","FromId": "Person_3","ToId": "Person_39","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_40","FromId": "Person_3","ToId": "Person_40","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_41","FromId": "Person_3","ToId": "Person_41","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_42","FromId": "Person_3","ToId": "Person_42","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_43","FromId": "Person_3","ToId": "Person_43","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_44","FromId": "Person_3","ToId": "Person_44","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_45","FromId": "Person_3","ToId": "Person_45","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_46","FromId": "Person_3","ToId": "Person_46","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_47","FromId": "Person_4","ToId": "Person_47","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_48","FromId": "Person_4","ToId": "Person_48","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_49","FromId": "Person_4","ToId": "Person_49","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_50","FromId": "Person_4","ToId": "Person_50","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_51","FromId": "Person_4","ToId": "Person_51","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_52","FromId": "Person_4","ToId": "Person_52","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_53","FromId": "Person_4","ToId": "Person_53","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_54","FromId": "Person_4","ToId": "Person_54","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_55","FromId": "Person_4","ToId": "Person_55","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_56","FromId": "Person_4","ToId": "Person_56","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_57","FromId": "Person_4","ToId": "Person_57","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_58","FromId": "Person_4","ToId": "Person_58","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_59","FromId": "Person_4","ToId": "Person_59","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_60","FromId": "Person_4","ToId": "Person_60","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_61","FromId": "Person_4","ToId": "Person_61","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_62","FromId": "Person_5","ToId": "Person_62","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_63","FromId": "Person_5","ToId": "Person_63","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_64","FromId": "Person_5","ToId": "Person_64","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_65","FromId": "Person_5","ToId": "Person_65","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_66","FromId": "Person_5","ToId": "Person_66","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_67","FromId": "Person_5","ToId": "Person_67","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_68","FromId": "Person_5","ToId": "Person_68","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_69","FromId": "Person_5","ToId": "Person_69","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_70","FromId": "Person_5","ToId": "Person_70","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_71","FromId": "Person_5","ToId": "Person_71","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_72","FromId": "Person_5","ToId": "Person_72","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_73","FromId": "Person_5","ToId": "Person_73","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_74","FromId": "Person_5","ToId": "Person_74","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_75","FromId": "Person_5","ToId": "Person_75","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_76","FromId": "Person_5","ToId": "Person_76","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_77","FromId": "Person_6","ToId": "Person_77","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_78","FromId": "Person_6","ToId": "Person_78","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_79","FromId": "Person_6","ToId": "Person_79","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_80","FromId": "Person_6","ToId": "Person_80","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_81","FromId": "Person_6","ToId": "Person_81","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_82","FromId": "Person_6","ToId": "Person_82","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_83","FromId": "Person_6","ToId": "Person_83","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_84","FromId": "Person_6","ToId": "Person_84","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_85","FromId": "Person_6","ToId": "Person_85","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_86","FromId": "Person_6","ToId": "Person_86","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_87","FromId": "Person_6","ToId": "Person_87","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_88","FromId": "Person_6","ToId": "Person_88","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_89","FromId": "Person_6","ToId": "Person_89","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_90","FromId": "Person_6","ToId": "Person_90","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_91","FromId": "Person_6","ToId": "Person_91","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_92","FromId": "Person_7","ToId": "Person_92","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_93","FromId": "Person_7","ToId": "Person_93","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_94","FromId": "Person_7","ToId": "Person_94","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_95","FromId": "Person_7","ToId": "Person_95","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_96","FromId": "Person_7","ToId": "Person_96","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_97","FromId": "Person_7","ToId": "Person_97","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_98","FromId": "Person_7","ToId": "Person_98","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_99","FromId": "Person_7","ToId": "Person_99","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]},
{"Id":"Person_1_Person_100","FromId": "Person_7","ToId": "Person_100","LinkTypeId": "Person_Person","PropertyValues": [{"Key": "type","Value": "职场"},{"Key": "relation","Value": "同事"}]}




    ]
}
