//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChenRui.SL.Diagram.Layout {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChenRui.SL.Diagram.Layout.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Aggressive 的本地化字符串。
        /// </summary>
        public static string Aggressive {
            get {
                return ResourceManager.GetString("Aggressive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alignment 的本地化字符串。
        /// </summary>
        public static string Alignment {
            get {
                return ResourceManager.GetString("Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alternating 的本地化字符串。
        /// </summary>
        public static string Alternating {
            get {
                return ResourceManager.GetString("Alternating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Angel Speed 的本地化字符串。
        /// </summary>
        public static string AngelSpeed {
            get {
                return ResourceManager.GetString("AngelSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Angle 的本地化字符串。
        /// </summary>
        public static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Angle Range 的本地化字符串。
        /// </summary>
        public static string AngleRange {
            get {
                return ResourceManager.GetString("AngleRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arc Spacing Ratio 的本地化字符串。
        /// </summary>
        public static string ArcSpacingRatio {
            get {
                return ResourceManager.GetString("ArcSpacingRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ascending 的本地化字符串。
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aspect Ratio 的本地化字符串。
        /// </summary>
        public static string AspectRatio {
            get {
                return ResourceManager.GetString("AspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Block 的本地化字符串。
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom 的本地化字符串。
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom Right Bus 的本地化字符串。
        /// </summary>
        public static string BottomRightBus {
            get {
                return ResourceManager.GetString("BottomRightBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Breadth Limit 的本地化字符串。
        /// </summary>
        public static string BreadthLimit {
            get {
                return ResourceManager.GetString("BreadthLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bus 的本地化字符串。
        /// </summary>
        public static string Bus {
            get {
                return ResourceManager.GetString("Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center Children 的本地化字符串。
        /// </summary>
        public static string CenterChildren {
            get {
                return ResourceManager.GetString("CenterChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center Node 的本地化字符串。
        /// </summary>
        public static string CenterNode {
            get {
                return ResourceManager.GetString("CenterNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center Node Distance 的本地化字符串。
        /// </summary>
        public static string CenterNodeDistance {
            get {
                return ResourceManager.GetString("CenterNodeDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center Node Distance Ratio 的本地化字符串。
        /// </summary>
        public static string CenterNodeDistanceRatio {
            get {
                return ResourceManager.GetString("CenterNodeDistanceRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center Node Placement 的本地化字符串。
        /// </summary>
        public static string CenterNodePlacement {
            get {
                return ResourceManager.GetString("CenterNodePlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center Node Type 的本地化字符串。
        /// </summary>
        public static string CenterNodeType {
            get {
                return ResourceManager.GetString("CenterNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center Subtrees 的本地化字符串。
        /// </summary>
        public static string CenterSubtrees {
            get {
                return ResourceManager.GetString("CenterSubtrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Circle Spacing Ratio 的本地化字符串。
        /// </summary>
        public static string CircleSpacingRatio {
            get {
                return ResourceManager.GetString("CircleSpacingRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Count 的本地化字符串。
        /// </summary>
        public static string ColumnCount {
            get {
                return ResourceManager.GetString("ColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Spacing 的本地化字符串。
        /// </summary>
        public static string ColumnSpacing {
            get {
                return ResourceManager.GetString("ColumnSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compaction 的本地化字符串。
        /// </summary>
        public static string Compaction {
            get {
                return ResourceManager.GetString("Compaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Depth First In 的本地化字符串。
        /// </summary>
        public static string DepthFirstIn {
            get {
                return ResourceManager.GetString("DepthFirstIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Depth First Out 的本地化字符串。
        /// </summary>
        public static string DepthFirstOut {
            get {
                return ResourceManager.GetString("DepthFirstOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Descending 的本地化字符串。
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direction 的本地化字符串。
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distance 的本地化字符串。
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Electrical Charge 的本地化字符串。
        /// </summary>
        public static string ElectricalCharge {
            get {
                return ResourceManager.GetString("ElectricalCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End 的本地化字符串。
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First Circle Fix Radius 的本地化字符串。
        /// </summary>
        public static string FirstCircleFixRadius {
            get {
                return ResourceManager.GetString("FirstCircleFixRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First Circle Node Count 的本地化字符串。
        /// </summary>
        public static string FirstCircleNodeCount {
            get {
                return ResourceManager.GetString("FirstCircleNodeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First Circle Radius 的本地化字符串。
        /// </summary>
        public static string FirstCircleRadius {
            get {
                return ResourceManager.GetString("FirstCircleRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First Circle Radius Ratio 的本地化字符串。
        /// </summary>
        public static string FirstCircleRadiusRatio {
            get {
                return ResourceManager.GetString("FirstCircleRadiusRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First Node 的本地化字符串。
        /// </summary>
        public static string FirstNode {
            get {
                return ResourceManager.GetString("FirstNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fix Column Count 的本地化字符串。
        /// </summary>
        public static string FixColumnCount {
            get {
                return ResourceManager.GetString("FixColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fix Radius 的本地化字符串。
        /// </summary>
        public static string FixRadius {
            get {
                return ResourceManager.GetString("FixRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fix Row Count 的本地化字符串。
        /// </summary>
        public static string FixRowCount {
            get {
                return ResourceManager.GetString("FixRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forwards 的本地化字符串。
        /// </summary>
        public static string Forwards {
            get {
                return ResourceManager.GetString("Forwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Padding 的本地化字符串。
        /// </summary>
        public static string GroupPadding {
            get {
                return ResourceManager.GetString("GroupPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horizontal Spacing 的本地化字符串。
        /// </summary>
        public static string HorizontalSpacing {
            get {
                return ResourceManager.GetString("HorizontalSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialize 的本地化字符串。
        /// </summary>
        public static string Initialize {
            get {
                return ResourceManager.GetString("Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Center Node Left 的本地化字符串。
        /// </summary>
        public static string IsCenterNodeLeft {
            get {
                return ResourceManager.GetString("IsCenterNodeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Center Node Top 的本地化字符串。
        /// </summary>
        public static string IsCenterNodeTop {
            get {
                return ResourceManager.GetString("IsCenterNodeTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Clockwise 的本地化字符串。
        /// </summary>
        public static string IsClockwise {
            get {
                return ResourceManager.GetString("IsClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Continuous 的本地化字符串。
        /// </summary>
        public static string IsContinuous {
            get {
                return ResourceManager.GetString("IsContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Node 的本地化字符串。
        /// </summary>
        public static string LastNode {
            get {
                return ResourceManager.GetString("LastNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Parents 的本地化字符串。
        /// </summary>
        public static string LastParents {
            get {
                return ResourceManager.GetString("LastParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layered 的本地化字符串。
        /// </summary>
        public static string Layered {
            get {
                return ResourceManager.GetString("Layered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layering 的本地化字符串。
        /// </summary>
        public static string Layering {
            get {
                return ResourceManager.GetString("Layering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layer Spacing 的本地化字符串。
        /// </summary>
        public static string LayerSpacing {
            get {
                return ResourceManager.GetString("LayerSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layer Spacing Parent Overlap); 的本地化字符串。
        /// </summary>
        public static string LayerSpacingParentOverlap {
            get {
                return ResourceManager.GetString("LayerSpacingParentOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left 的本地化字符串。
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Less 的本地化字符串。
        /// </summary>
        public static string Less {
            get {
                return ResourceManager.GetString("Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Longest Path Sink 的本地化字符串。
        /// </summary>
        public static string LongestPathSink {
            get {
                return ResourceManager.GetString("LongestPathSink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Longest Path Source 的本地化字符串。
        /// </summary>
        public static string LongestPathSource {
            get {
                return ResourceManager.GetString("LongestPathSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Link Count Node 的本地化字符串。
        /// </summary>
        public static string MaxLinkCountNode {
            get {
                return ResourceManager.GetString("MaxLinkCountNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More 的本地化字符串。
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Naive 的本地化字符串。
        /// </summary>
        public static string Naive {
            get {
                return ResourceManager.GetString("Naive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node Indent 的本地化字符串。
        /// </summary>
        public static string NodeIndent {
            get {
                return ResourceManager.GetString("NodeIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node Indent Past Parent 的本地化字符串。
        /// </summary>
        public static string NodeIndentPastParent {
            get {
                return ResourceManager.GetString("NodeIndentPastParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node Spacing 的本地化字符串。
        /// </summary>
        public static string NodeSpacing {
            get {
                return ResourceManager.GetString("NodeSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimal Link Length 的本地化字符串。
        /// </summary>
        public static string OptimalLinkLength {
            get {
                return ResourceManager.GetString("OptimalLinkLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack Expand 的本地化字符串。
        /// </summary>
        public static string PackExpand {
            get {
                return ResourceManager.GetString("PackExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack Median 的本地化字符串。
        /// </summary>
        public static string PackMedian {
            get {
                return ResourceManager.GetString("PackMedian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pack Straighten 的本地化字符串。
        /// </summary>
        public static string PackStraighten {
            get {
                return ResourceManager.GetString("PackStraighten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Radius 的本地化字符串。
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Radius Init 的本地化字符串。
        /// </summary>
        public static string RadiusInit {
            get {
                return ResourceManager.GetString("RadiusInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Radius Pow 的本地化字符串。
        /// </summary>
        public static string RadiusPow {
            get {
                return ResourceManager.GetString("RadiusPow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reverse 的本地化字符串。
        /// </summary>
        public static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root Only 的本地化字符串。
        /// </summary>
        public static string RootOnly {
            get {
                return ResourceManager.GetString("RootOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row Count 的本地化字符串。
        /// </summary>
        public static string RowCount {
            get {
                return ResourceManager.GetString("RowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row Indent 的本地化字符串。
        /// </summary>
        public static string RowIndent {
            get {
                return ResourceManager.GetString("RowIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row Spacing 的本地化字符串。
        /// </summary>
        public static string RowSpacing {
            get {
                return ResourceManager.GetString("RowSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorting 的本地化字符串。
        /// </summary>
        public static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spring Length 的本地化字符串。
        /// </summary>
        public static string SpringLength {
            get {
                return ResourceManager.GetString("SpringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spring Stiffness 的本地化字符串。
        /// </summary>
        public static string SpringStiffness {
            get {
                return ResourceManager.GetString("SpringStiffness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Angle 的本地化字符串。
        /// </summary>
        public static string StartAngle {
            get {
                return ResourceManager.GetString("StartAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 的本地化字符串。
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top Left Bus 的本地化字符串。
        /// </summary>
        public static string TopLeftBus {
            get {
                return ResourceManager.GetString("TopLeftBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tree Style 的本地化字符串。
        /// </summary>
        public static string TreeStyle {
            get {
                return ResourceManager.GetString("TreeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertical Spacing 的本地化字符串。
        /// </summary>
        public static string VerticalSpacing {
            get {
                return ResourceManager.GetString("VerticalSpacing", resourceCulture);
            }
        }
    }
}
